# Generated by Django 3.1 on 2020-12-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbasket',
            old_name='products',
            new_name='product',
        ),
    ]
