# Generated by Django 3.1 on 2020-12-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201221_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbasket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
