# Generated by Django 3.1.5 on 2021-01-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(blank=True, choices=[('Kırmızı', 'KIRMIZI'), ('MAVİ', 'MAVİ'), ('YEŞİL', 'YEŞİL')], max_length=10, verbose_name='Ürün Durumu'),
        ),
    ]
