# Generated by Django 3.1.5 on 2021-01-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderproduct_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
    ]
