# Generated by Django 3.1 on 2021-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210110_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/users/333.jpg', upload_to='images/', verbose_name='Ürün Fotoğrafı'),
        ),
    ]
