# Generated by Django 3.1.5 on 2021-01-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210110_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ürün İsmi'),
        ),
    ]
